name: whote_is_there
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.1.0
  bluetooth_low_energy: ^6.0.0
  permission_handler: ^12.0.1
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  path: ^1.9.1
  google_fonts: ^6.1.0
  vector_math: ^2.2.0
  provider: ^6.1.5+1
  flutter_phoenix: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

dependency_overrides: 
  flutter_blue_plus_winrt: 
    git:
      url: git@github.com:MichJadams/flutter_blue_plus_winrt.git
      ref: windows_fixes 
  bluetooth_low_energy_windows:
    git:
      url: https://github.com/MichJadams/bluetooth_low_energy.git
      ref: updated-varient-arg-access
      path: bluetooth_low_energy_windows

flutter:
  uses-material-design: true
  assets:
  - assets/
